// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SenseFin.Infrastructure.Persistence;

#nullable disable

namespace SenseFin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SenseFinDbContext))]
    [Migration("20260516161920_AddBlacklistEntity")]
    partial class AddBlacklistEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SenseFin.Domain.Aggregates.Blacklist.BlacklistedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountIdentifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentifierType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("IncidentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_BlacklistedAccounts_IsActive");

                    b.HasIndex("Reason")
                        .HasDatabaseName("IX_BlacklistedAccounts_Reason");

                    b.HasIndex("AccountIdentifier", "IdentifierType")
                        .HasDatabaseName("IX_BlacklistedAccounts_Identifier");

                    b.ToTable("BlacklistedAccounts", (string)null);
                });

            modelBuilder.Entity("SenseFin.Domain.Aggregates.RiskProfile.RiskProfileAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("AverageRiskScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentRiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalEvaluations")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("IX_RiskProfiles_AccountId");

                    b.ToTable("RiskProfiles", (string)null);
                });

            modelBuilder.Entity("SenseFin.Domain.Aggregates.Transaction.TransactionAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MerchantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReceiverAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReceiverIban")
                        .HasColumnType("text");

                    b.Property<string>("SenderAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SenderDeviceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SenderIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("TremorScore")
                        .HasColumnType("double precision");

                    b.Property<double?>("TypingScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverAccountId")
                        .HasDatabaseName("IX_Transactions_ReceiverAccountId");

                    b.HasIndex("SenderAccountId")
                        .HasDatabaseName("IX_Transactions_SenderAccountId");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("IX_Transactions_TransactionDate");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("SenseFin.Domain.Aggregates.RiskProfile.RiskProfileAggregate", b =>
                {
                    b.OwnsMany("SenseFin.Domain.Aggregates.RiskProfile.RiskScoreEntry", "RiskScores", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("EvaluatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Reason")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<Guid>("RiskProfileId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Score")
                                .HasColumnType("double precision");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("RiskProfileId")
                                .HasDatabaseName("IX_RiskScoreEntries_RiskProfileId");

                            b1.HasIndex("TransactionId")
                                .HasDatabaseName("IX_RiskScoreEntries_TransactionId");

                            b1.ToTable("RiskScoreEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RiskProfileId");
                        });

                    b.Navigation("RiskScores");
                });

            modelBuilder.Entity("SenseFin.Domain.Aggregates.Transaction.TransactionAggregate", b =>
                {
                    b.OwnsOne("SenseFin.Domain.Aggregates.Transaction.GeoLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("TransactionAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("LocationCity");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LocationCountry");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Longitude");

                            b1.HasKey("TransactionAggregateId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionAggregateId");
                        });

                    b.OwnsOne("SenseFin.Domain.Aggregates.Transaction.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("TransactionAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(false)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("TransactionAggregateId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionAggregateId");
                        });

                    b.Navigation("Location");

                    b.Navigation("Money")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
